[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = false

[profile.default.optimizer]
enabled = true
runs = 200

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "short"

